name: currency_converter
description: A simple currency converter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.7.0

  # MobX для управления состоянием (MVVM)
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+1

  # Для HTTP запросов
  dio: ^5.4.0

  # Для работы с датами
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Генераторы кода
  build_runner: ^2.4.8          # Инструмент для генерации кода
  mobx_codegen: ^2.6.0+1        # Генератор кода для MobX
  json_serializable: ^6.8.0     # Генератор для JSON сериализации
  analyzer: ^6.4.0

  flutter_lints: ^3.0.0

flutter:
  generate: true