name: currency_converter
description: A simple currency converter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # MobX для управления состоянием (MVVM)
  mobx: ^2.3.0+1              # Основная библиотека MobX
  flutter_mobx: ^2.2.0+1       # Интеграция с Flutter (Observer виджет)

  # AutoRouter для навигации
  auto_route: ^7.8.4           # Основная библиотека AutoRouter

  # Для HTTP запросов
  dio: ^5.4.0                  # Продвинутый HTTP клиент

  # Для работы с датами
  intl: ^0.18.1                # Форматирование дат

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Генераторы кода
  build_runner: ^2.4.8          # Инструмент для генерации кода
  mobx_codegen: ^2.6.0+1        # Генератор кода для MobX
  auto_route_generator: ^7.3.2  # Генератор кода для AutoRouter

  flutter_lints: ^3.0.0